BEGIN TRANSACTION;
INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

INSERT INTO contest_categories (category_name)
VALUES
('Band'),
('Sports'),
('Academic'),
('Coding'),
('Startup Pitches');

INSERT INTO contests (contest_name, contest_description, contest_date_time, contest_location, category_id, image_url) 
VALUES 
('Columbus Area Band Contest', 'The Columbus Area Band Contest is an exhilarating music competition celebrating the vibrant and diverse local band scene in Columbus, Ohio. This event brings together a wide array of musical talents, from emerging garage bands to more established groups, showcasing a variety of genres including rock, jazz, indie, and more. Participants will compete for the title of "Columbus''s Best Band," along with other exciting prizes. Each band will have a set time to perform their best pieces in front of an enthusiastic audience and a panel of esteemed judges from the music industry. In addition to the musical performances, the event will feature local food trucks, merchandise stalls, and interactive booths, making it a perfect outing for music lovers of all ages.',
 '2024-04-10', 'Columbus, OH', 1, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702572051/contests_app/artwgdrgwzmqo8kmdunt.png'),
('Tech Elevator Capstone Expo', 'The Tech Elevator Capstone Expo is the culminating event of the 14-week coding BootCamp, where Tech Elevator students showcase their skills and accomplishments through the presentation of full-stack web applications. In this intensive final project, students are divided into teams, each tasked with conceiving, designing, and implementing a comprehensive web application within a tight two-week timeframe. The expo serves as a platform for students to demonstrate their proficiency in various programming languages, frameworks, and technologies learned throughout the BootCamp. Attendees have the opportunity to witness firsthand the innovative solutions and creative applications developed by these teams, highlighting the practical application of their newly acquired coding and development skills. The Capstone Expo not only celebrates the students'' journey and achievements but also provides a valuable opportunity for networking and interaction within the tech community.',
 '2023-12-15', 'Columbus, OH', 4, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571835/contests_app/ktvqg0r4scfywcrdvvxg.jpg');

INSERT INTO participants (participant_name, participant_description, member_count, score, contest_id, image_url, votes) 
VALUES 
('The Electric Echoes', 'An innovative indie rock band known for their electrifying performances and unique soundscapes.', 4, NULL, 1, null, 0),
('Jazz Junction', 'A group of seasoned jazz musicians blending classic and modern jazz styles.', 5, NULL, 1, null, 0),
('Harmony Hive', 'A dynamic pop band with catchy tunes and vibrant stage presence.', 6, NULL, 1, null, 0),
('Bluegrass Rebels', 'A bluegrass band with a contemporary twist, known for their soulful melodies.', 3, NULL, 1, null, 0),
('The Velvet Suns', 'A rock band with a flair for dramatic, high-energy performances.', 5, NULL, 1, null, 0),
('Sonic Synthesis', 'An experimental band merging electronic and acoustic sounds.', 4, NULL, 1, null, 0),
('The Groove Makers', 'A funk band known for their groovy basslines and infectious rhythms.', 6, NULL, 1, null, 0),
('Lyrical Legends', 'A hip-hop group with sharp lyrics and powerful beats.', 2, NULL, 1, null, 0),
('The Serene Strings', 'A classical ensemble bringing a fresh perspective to traditional compositions.', 4, NULL, 1, null, 0),
('Rhythm Raiders', 'A reggae band infusing classic reggae with modern influences.', 5, NULL, 1, null, 0),
('Team Alpha', 'ROOM 205 - Protien Taggin | Protein Capture Science (PCS) provides tools and technology to assist in the purification of proteins. They do this by initially “binding” their proprietary protein marker (tag) to the first amino acid at the beginning of the target protein. The tag, like a hook, allows target proteins to be “caught” like a fish on the hook during the purification process while other impurities are washed away from a stream. In the final stage, target proteins are simply “let go” from the “hook” (a tag), and only pure target protein is harvested. This technique is used on a small scale in biotech labs to purify protein-based biopharmaceuticals, and it was developed as a part of a DARPA project focused on the creation of a small “suitcase” for rapid medicine production for soldiers in action. DARPA is known for futuristic projects that can benefit the U.S. Army, including developing “cyborg insects,” “houses that repair themselves,” and robotic infantry mules.
During the development process, it was noted that the first two amino acids located at the beginning of the target protein affect the separation of the target protein from the tag. This phenomenon can also be predicted based on historical experimental data. An application can be developed to quickly predict if that separation can be fast, slow, or none based on a wide range of target proteins, which need to be purified. In this case, the impact on the ability to rapidly produce medicines can be extraordinary, especially in a time of emergency preparedness.
The application allows users to import information about a target protein. It provides the ability to show an ordered list of the possible first amino acid pair replacement at the beginning of the target protein, providing suggestions about optimal separation of the tag from the target protein.', 3, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571601/contests_app/kqbspfgkoggg8nnh70ak.jpg', 0),
('Team Bravo', 'ROOM 205 - Brewery Finder | The site shows information about breweries and beers. Beer lovers can view information about breweries and beers, while brewers can update the information about their produces. Administrators can add breweries', 3, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571600/contests_app/jrhf2g5wsib5stmcamkb.jpg', 0),
('Team Charlie', 'ROOM 205 - Code Catalog | The application stores a catalog and examples of coding snippets. The catalog would support general-purpose programming languages and scripts for environments that operate with those languages (SQL, JavaScript, JSTL, etc). The application would initially be populated with basic examples and allow users to submit examples. Public examples would have an admin providing curation of the list. The application would start off with simple examples of base concepts like loops, branching, arrays, etc. and then move on to examples which combine or nest two of the concepts. There would be links on each example page which take the user to related, combined, or nested examples.', 3, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571600/contests_app/g3uvqmme5c4omfwknxmc.jpg', 0),
('Team Delta', 'ROOM 205 - Meal Planner | Meal planning is hard. You have to come up with what to make based on what is in your pantry, make it to the store, and then keep track of all of the different ways to prepare the food. The meal planner application allows users to create their own library of recipes and plan meals for the week using existing recipes (and ingredients).', 3, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571600/contests_app/sz0gadwoh54pewozi4vb.jpg', 0),
('Team Echo', 'ROOM 104 - Flashcard Study App | Users can create flashcard decks and then add and modify cards. Users can use flashcard decks to student material on cards. Optionally, users can use the cards in multiple ways and share cards with others.', 3, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571599/contests_app/dfjsdgn9naxazo0yddxc.jpg', 0),
('Team Foxtrot', 'ROOM 104 - Flashcard Study App | Users can create flashcard decks and then add and modify cards. Users can use flashcard decks to student material on cards. Optionally, users can use the cards in multiple ways and share cards with others.', 4, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571601/contests_app/l9m7pwdao7p99tvdllwp.jpg', 0),
('Team Golf', 'ROOM 104 - Protien Tagging | Protein Capture Science (PCS) provides tools and technology to assist in the purification of proteins. They do this by initially “binding” their proprietary protein marker (tag) to the first amino acid at the beginning of the target protein. The tag, like a hook, allows target proteins to be “caught” like a fish on the hook during the purification process while other impurities are washed away from a stream. In the final stage, target proteins are simply “let go” from the “hook” (a tag), and only pure target protein is harvested. This technique is used on a small scale in biotech labs to purify protein-based biopharmaceuticals, and it was developed as a part of a DARPA project focused on the creation of a small “suitcase” for rapid medicine production for soldiers in action. DARPA is known for futuristic projects that can benefit the U.S. Army, including developing “cyborg insects,” “houses that repair themselves,” and robotic infantry mules.
During the development process, it was noted that the first two amino acids located at the beginning of the target protein affect the separation of the target protein from the tag. This phenomenon can also be predicted based on historical experimental data. An application can be developed to quickly predict if that separation can be fast, slow, or none based on a wide range of target proteins, which need to be purified. In this case, the impact on the ability to rapidly produce medicines can be extraordinary, especially in a time of emergency preparedness.
The application allows users to import information about a target protein. It provides the ability to show an ordered list of the possible first amino acid pair replacement at the beginning of the target protein, providing suggestions about optimal separation of the tag from the target protein.', 3, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571599/contests_app/n1gzunq8q3vqba54vv7t.jpg', 0),
('Team Hotel', 'ROOM 104 - Workout Companion | The workout companion is the digital assistant to help gym attendees keep track of the time spent at the gym and work done using workout machines or weights.', 4, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571602/contests_app/gagaanoeekiidvkkzvd6.jpg', 0),
('Team India', 'ROOM 104 - Cover My Shift | In certain industries such as education, retail, and food service, there are often situations when a person needs to take time off. Many companies make employees rummage through complicated staffing documents (digital or physical) to find other employees to cover their shift(s). This is also an extra burden on managers often trying to be flexible and help employees and maintain appropriate staffing. This project is to design a service that can solve this problem of quickly and efficiently meeting the needs of employees and managers. Suggested and created by Gregg Sanders', 4, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571599/contests_app/qmv2mxt0gepfu1givmkw.jpg', 0),
('Team Juliett', 'ROOM 121 - Meal Planner | Meal planning is hard. You have to come up with what to make based on what is in your pantry, make it to the store, and then keep track of all of the different ways to prepare the food. The meal planner application allows users to create their own library of recipes and plan meals for the week using existing recipes (and ingredients).', 4, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571601/contests_app/xjh7n8sccfzgu9yvu9ap.jpg', 0),
('Team Kilo', 'ROOM 121 - Protien Taggin | Protein Capture Science (PCS) provides tools and technology to assist in the purification of proteins. They do this by initially “binding” their proprietary protein marker (tag) to the first amino acid at the beginning of the target protein. The tag, like a hook, allows target proteins to be “caught” like a fish on the hook during the purification process while other impurities are washed away from a stream. In the final stage, target proteins are simply “let go” from the “hook” (a tag), and only pure target protein is harvested. This technique is used on a small scale in biotech labs to purify protein-based biopharmaceuticals, and it was developed as a part of a DARPA project focused on the creation of a small “suitcase” for rapid medicine production for soldiers in action. DARPA is known for futuristic projects that can benefit the U.S. Army, including developing “cyborg insects,” “houses that repair themselves,” and robotic infantry mules.
During the development process, it was noted that the first two amino acids located at the beginning of the target protein affect the separation of the target protein from the tag. This phenomenon can also be predicted based on historical experimental data. An application can be developed to quickly predict if that separation can be fast, slow, or none based on a wide range of target proteins, which need to be purified. In this case, the impact on the ability to rapidly produce medicines can be extraordinary, especially in a time of emergency preparedness.
The application allows users to import information about a target protein. It provides the ability to show an ordered list of the possible first amino acid pair replacement at the beginning of the target protein, providing suggestions about optimal separation of the tag from the target protein.', 4, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571598/contests_app/qeylvflhw0upghzyjb5f.jpg', 0),
('Team Lima', 'ROOM 121 - City Tours | Show landmarks and locations that visitors might want to visit. Allow users to plan a trip that includes selected locations', 4, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571599/contests_app/fqmapky5k2u3uhzgkqti.jpg', 0),
('Team Mike', 'ROOM 121 - Contest Management | Whether it is Marching Bands, Model UN, Robotics, or Cheerleading, people are gathering and competing. The purpose of this application is to create and administer those contests. Suggested and created by Forrest Yankey', 3, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571600/contests_app/azoyemvpw7vclafw5xmf.jpg', 0),
('Team November', 'ROOM 121 - Meal Planner | Meal planning is hard. You have to come up with what to make based on what is in your pantry, make it to the store, and then keep track of all of the different ways to prepare the food. The meal planner application allows users to create their own library of recipes and plan meals for the week using existing recipes (and ingredients).', 4, NULL, 2, 'https://res.cloudinary.com/dmptbrbof/image/upload/v1702571601/contests_app/ohtyo50lybvwzyqxxyoa.jpg', 0);

INSERT INTO time_slots (contest_id, participant_id, time_slot)
VALUES
(1, 1, '08:00:00'),
(1, 2, '09:00:00'),
(1, 3, '10:00:00'),
(1, 4, '11:00:00'),
(1, 5, '12:00:00'),
(1, 6, '13:00:00'),
(1, 7, '14:00:00'),
(1, 8, '15:00:00'),
(1, 9, '16:00:00'),
(1, 10, '17:00:00');

COMMIT TRANSACTION;